# Generated by Django 4.2.9 on 2025-09-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('porcentaje_ganancia', models.DecimalField(decimal_places=2, default=20.0, help_text='Porcentaje de ganancia aplicado al precio de compra.', max_digits=5)),
                ('permitir_descuentos', models.BooleanField(default=True)),
                ('porcentaje_descuento_maximo', models.DecimalField(decimal_places=2, default=10.0, help_text='Porcentaje máximo de descuento permitido.', max_digits=5)),
                ('nombre_negocio', models.CharField(default='Mi Negocio', max_length=100)),
                ('moneda', models.CharField(default='Bs.', max_length=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración',
                'verbose_name_plural': 'Configuraciones',
            },
        ),
    ]
