# Generated by Django 4.2.9 on 2025-10-01 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_configuracion_direccion_configuracion_nit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
