# Generated by Django 4.2.9 on 2025-10-03 04:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_ganancia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del trabajo o servicio', max_length=150)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles opcionales', null=True)),
                ('costo', models.DecimalField(decimal_places=2, help_text='Costo del trabajo', max_digits=10)),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha de registro del trabajo')),
            ],
        ),
    ]
